---
title: "analysis.rmd"
output: pdf_document
date: "2025-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, comment=NA}
# packages
library(ggplot2)
library(dplyr)
library(car)
library(reshape2)
library(olsrr)
```

```{r}
df <- read.csv("main.csv")
head(df)
```

# Initial Model Creation

```{r}
initial_model <- lm(avg_salary_millions ~ MP + PTS + FG_pct + FTA + TRB + AST + stocks + Value_Billions + (PTS * FTA), data = df)
summary(initial_model)
```
# VIF Analysis
```{r}
vif_values <- vif(initial_model)
print(vif_values)

# high vifs detected, remove
vif_less <- lm(avg_salary_millions ~ MP + PTS + FG_pct + FTA + TRB + AST + stocks + Value_Billions, data = df)
print(vif(vif_less))
```
# Stepwise
```{r}
ols_step_both_p(vif_less,p_ent=0.15,p_rem=0.15,details=T)
```

# T-Test Quant Only
```{r}
summary(vif_less)
```

# New Model as a Result of Test
```{r}
quant <- lm(avg_salary_millions ~ MP + PTS + TRB + AST, data = df)
summary(quant)
```

# Adding Qualitative Predictors
```{r}
quant_and_qual <- lm(avg_salary_millions ~ MP + PTS + TRB + AST + awards_1 + awards_2plus + Age_22_26 + Age_27_31 + Age_32_34 + Age_35_plus + Pos_PF + Pos_PG + Pos_SF + Pos_SG, data = df)
summary(quant_and_qual)
```

# ANOVA Test for reduced model (Awards)
```{r}
reduced_awards <- lm(avg_salary_millions ~ MP + PTS + TRB + AST + Age_22_26 + Age_27_31 + Age_32_34 + Age_35_plus + Pos_PF + Pos_PG + Pos_SF + Pos_SG, data = df)
anova(reduced_awards, quant_and_qual)
```

# ANOVA Test for reduced model (Age)
```{r}
reduced_age <- lm(avg_salary_millions ~ MP + PTS + TRB + AST + awards_1 + awards_2plus + Pos_PF + Pos_PG + Pos_SF + Pos_SG, data = df)
anova(reduced_age, quant_and_qual)
```

# ANOVA Test for reduced model (Pos)
```{r}
reduced_pos <- lm(avg_salary_millions ~ MP + PTS + TRB + AST + awards_1 + awards_2plus + Age_22_26 + Age_27_31 + Age_32_34 + Age_35_plus, data = df)
anova(reduced_pos, quant_and_qual)
```

# Confidence/Prediction Intervals
```{r}
conf <- confint(quant_and_qual, level = 0.95)
conf

# add prediction
```

# Residual Analysis
```{r}
# Cooks Distance Thresholds
plot(quant_and_qual,which=4)

# Leverage vs Studentized Residuals
influencePlot(quant_and_qual,fill=F)

# Deleted Studentized Residuals vs Predicted values
ols_plot_resid_stud_fit(quant_and_qual)
```