---
title: "model.rmd"
output: pdf_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, comment=NA}
# packages
library(ggplot2)
library(dplyr)
library(car)
library(reshape2)
```

```{r}
df <- read.csv("cleaned_data.csv")
head(df)
```

Getting rid of unnecessary columns (only need to run once, saves the updated csv)
```{r}
df <- df %>%
  select(-Awards, -GS, -FGA, -n_awards_won, -awards_0, -Age)
write.csv(df, "cleaned_data_updated.csv", row.names = FALSE)
```
Checking for correct data
```{r}
head(df)
```

Converting Age and awards into one variable with levels
```{r}
df$Age <- apply(df[, c("Age_22_26", "Age_27_31", "Age_32_34", "Age_35_plus")], 1, function(row) {
  level <- which(row == 1)
  if (length(level) == 0) return(NA)
  return(paste0("Age_", level))
})

df$Age <- factor(df$Age)

df$Awards <- apply(df[, c("awards_1", "awards_2plus")], 1, function(row) {
  level <- which(row == 1)
  if (length(level) == 0) return("0 awards")   # if neither dummy is 1
  return(c("1 award", "2+ awards")[level])
})

df$Awards <- factor(df$Awards)
head(df)
```

```{r}
ggplot(df, aes(x = avg_salary_millions)) + geom_histogram(binwidth = 1, fill = "blue", color = "black") + labs(title = "Distribution of Average Salaries (Millions)", x = "Average Salary (Millions)", y = "Count") + theme_minimal()
```

```{r}
numeric_cols <- df %>%
  select(-avg_salary_millions)

numeric_cols <- numeric_cols %>% select(where(is.numeric))

cor_matrix <- round(cor(numeric_cols, use = "complete.obs"), 2)

cor_matrix
```

```{r}
cor_melt <- melt(cor_matrix)
ggplot(cor_melt, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                       midpoint = 0, limit = c(-1,1), space = "Lab") +
  theme_minimal() +
  labs(title = "Correlation Heatmap", x = "", y = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
tapply(df$avg_salary_millions,df$Age,summary)
```
